/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Martin Trafas (https://sketchfab.com/Bexxie)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sony-trinitron-prl-dce3f599de634388aef1eaf49e3606bf
title: Sony Trinitron PRL
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sony_trinitron_prl.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[7.55, 36.07, 0.02]} rotation={[Math.PI / 2, 0, -3.14]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group scale={100}>
            <mesh geometry={nodes['0'].geometry} material={materials.TV_Screen_material} />
            <mesh geometry={nodes['1'].geometry} material={materials.TV_Body_material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sony_trinitron_prl.glb')
